# Generated by Django 5.1.2 on 2024-10-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audioname", models.CharField(max_length=100)),
                ("audio", models.FileField(upload_to="audio")),
            ],
        ),
    ]
